# Site settings
title: Klajdi Bejko
email: kbejko@gmail.com
description: Blog about web development, random stuff related to food or drink and to showcase work
baseurl: ""
url: "https://kbejko.github.io"
permalink: /journal/:title
twitter_username: klazhdi
github_username:  kbejko
# permalink: pretty

exclude: ["node_modules", "gulpfile.js", "package.json"]

collections:
  projects:
    output: true
    permalink: /:path
