# Site settings
title: Klajdi Bejko
email: kbejko@gmail.com
description: Klajdi's blog/portfolio
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kbejko.github.io" # the base hostname & protocol for your site
twitter_username: klazhdi
github_username:  kbejko

# Build settings

highlighter: pygments
