# Site settings
title: Jekyll and Klyde
email: jekyllandklyde@gmail.com
description: A blog/portfolio built in jekyll while learning jekyll.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kbejko.github.io" # the base hostname & protocol for your site
twitter_username: klazhdi
github_username:  kbejko

# Build settings

highlighter: pygments

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

prose:
  rooturl: '_posts'
  siteurl: 'http://prose.github.io/starter/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'media'
  ignore:
    - about.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
